// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ3ASAONb9lNdDpNAxo4_zBaM6TeiNzto',
    appId: '1:964867107500:web:82175a4b49e4d350708d09',
    messagingSenderId: '964867107500',
    projectId: 'flutter-chat-app-59660',
    authDomain: 'flutter-chat-app-59660.firebaseapp.com',
    storageBucket: 'flutter-chat-app-59660.firebasestorage.app',
    measurementId: 'G-F0GWMK6T3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEpkvjsSTAb0YF5X8RZ7KnVjQS0AOGhQg',
    appId: '1:964867107500:android:dcf3a8ed2c89af50708d09',
    messagingSenderId: '964867107500',
    projectId: 'flutter-chat-app-59660',
    storageBucket: 'flutter-chat-app-59660.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcrTn9kHRXy1LKa95fH8MG5s0ofDNcfZk',
    appId: '1:964867107500:ios:a637cb69fa40f951708d09',
    messagingSenderId: '964867107500',
    projectId: 'flutter-chat-app-59660',
    storageBucket: 'flutter-chat-app-59660.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrakcer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcrTn9kHRXy1LKa95fH8MG5s0ofDNcfZk',
    appId: '1:964867107500:ios:a637cb69fa40f951708d09',
    messagingSenderId: '964867107500',
    projectId: 'flutter-chat-app-59660',
    storageBucket: 'flutter-chat-app-59660.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrakcer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ3ASAONb9lNdDpNAxo4_zBaM6TeiNzto',
    appId: '1:964867107500:web:451d12b36980a0ce708d09',
    messagingSenderId: '964867107500',
    projectId: 'flutter-chat-app-59660',
    authDomain: 'flutter-chat-app-59660.firebaseapp.com',
    storageBucket: 'flutter-chat-app-59660.firebasestorage.app',
    measurementId: 'G-YTSEJZKX7L',
  );

}